export 'view/forgotPasswordPage/forgot_password.dart';
export 'view/forgotPasswordPage/new_password.dart';
export 'view/forgotPasswordPage/otp_password.dart';
export 'view/forgotPasswordPage/forgot_success.dart';
export 'view/splash_screen.dart';
export 'view/landingPage/landing_page.dart';
export 'view/LoginRegisterPage/login_register.dart';
export 'view/LoginRegisterPage/login_page.dart';
export 'view/LoginRegisterPage/register_page.dart';
